// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScheduleApp.Data;

#nullable disable

namespace ScheduleApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103225356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScheduleApp.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ScheduleItems_DayOfWeek_PeriodNumber");

                    b.ToTable("ScheduleItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Monday",
                            PeriodNumber = 2,
                            SubjectName = "Numerical Methods"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Monday",
                            PeriodNumber = 3,
                            SubjectName = "Computer Engineering"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Monday",
                            PeriodNumber = 5,
                            SubjectName = "Philosophy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Wednesday",
                            PeriodNumber = 3,
                            SubjectName = "Numerical Methods"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Wednesday",
                            PeriodNumber = 4,
                            SubjectName = "Intelligent Programming Systems"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Wednesday",
                            PeriodNumber = 6,
                            SubjectName = "Numerical Methods"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
